### ISSUE TITLE
Unable to compile with DDP on 2026.2.0

### ISSUE THREAD

**Issue by Test-subj** [KaufHA/common#34]
During compilation, it fails with errors about wifi.h

Here's how i have DDP in my config file:

external_components:
  - source:
      type: git
      url: https://github.com/KaufHA/common
    components: [ ddp ]
    refresh: always
ddp:

and here's where it tries to add DDP:

Compiling .pioenvs/strip01/src/esphome/components/ddp/ddp.cpp.o
Compiling .pioenvs/strip01/src/esphome/components/ddp/ddp_addressable_light_effect.cpp.o
Compiling .pioenvs/strip01/src/esphome/components/ddp/ddp_arduino.cpp.o
Compiling .pioenvs/strip01/src/esphome/components/ddp/ddp_light_effect.cpp.o
In file included from src/esphome/components/ddp/ddp.cpp:3:

src/esphome/components/ddp/ddp.h:9:10: fatal error: WiFi.h: No such file or directory

********************************************************************
* Looking for WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFi.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKWiFi.h
*
********************************************************************

    9 | #include <WiFi.h>
      |          ^~~~~~~~
compilation terminated.
*** [.pioenvs/strip01/src/esphome/components/ddp/ddp.cpp.o] Error 1
In file included from src/esphome/components/ddp/ddp_addressable_light_effect.cpp:3:
src/esphome/components/ddp/ddp.h:9:10: fatal error: WiFi.h: No such file or directory

********************************************************************
* Looking for WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFi.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKWiFi.h
*
********************************************************************

    9 | #include <WiFi.h>
      |          ^~~~~~~~
compilation terminated.
*** [.pioenvs/strip01/src/esphome/components/ddp/ddp_addressable_light_effect.cpp.o] Error 1
In file included from src/esphome/components/ddp/ddp_light_effect.cpp:3:
src/esphome/components/ddp/ddp.h:9:10: fatal error: WiFi.h: No such file or directory

********************************************************************
* Looking for WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFi.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKWiFi.h
*
********************************************************************

    9 | #include <WiFi.h>
      |          ^~~~~~~~
compilation terminated.
*** [.pioenvs/strip01/src/esphome/components/ddp/ddp_light_effect.cpp.o] Error 1
In file included from src/esphome/components/ddp/ddp_arduino.cpp:3:
src/esphome/components/ddp/ddp.h:9:10: fatal error: WiFi.h: No such file or directory

********************************************************************
* Looking for WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFi.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKWiFi.h
*
********************************************************************

    9 | #include <WiFi.h>
      |          ^~~~~~~~
compilation terminated.
*** [.pioenvs/strip01/src/esphome/components/ddp/ddp_arduino.cpp.o] Error 1
========================= [FAILED] Took 11.77 seconds =========================
